apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmc-deployment 
  labels:
    app: authmc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authmc
  template:
    metadata:
      labels:
        app: authmc
    spec:
      containers:
      - name: authmc
        image: pensioncr.azurecr.io/authmcimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret 
---
apiVersion: v1
kind: Service
metadata:
  name: authmcsvc
spec:
  selector:
    app: authmc
  type: LoadBalancer
  ports:
  - port: 80
  

